title: Witt Scafidi
description: "BBA in Business Analytics & Data Science at William & Mary | D1 Baseball"
baseurl: ""
url: "https://wittscafidi.github.io"

author:
  name: Witt Scafidi
  email: wittscafidi@gmail.com
  linkedin: "https://linkedin.com/in/witt-scafidi"
  phone: "(540) 333-4257"

plugins:
  - jekyll-seo-tag

markdown: kramdown
